/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MembershipPlan, GameDefinition, SurveyProvider, RewardItem, AffiliateOffer, AdvertiserCampaign } from './types';

export const MEMBERSHIP_PLANS: MembershipPlan[] = [
  {
    id: 'plan_daily',
    name: 'Daily Plan',
    priceINR: 10,
    coins: 100,
    durationDays: 1,
  },
  {
    id: 'plan_weekly',
    name: 'Weekly Plan',
    priceINR: 49,
    coins: 600,
    durationDays: 7,
  },
  {
    id: 'plan_monthly',
    name: 'Monthly Plan',
    priceINR: 149,
    coins: 2500,
    durationDays: 30,
  },
];

export const GAME_DEFINITIONS: GameDefinition[] = [
  {
    id: 'tap_target',
    name: 'Tap Target Hero',
    category: 'Arcade',
    imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    description: 'Test your reflexes! Hover/Click targets with lightning speed before the timer runs out. Get extra points for perfect combos.',
    activePlayers: 4520,
  },
  {
    id: 'memory_match',
    name: 'Crypto Matcher',
    category: 'Puzzle',
    imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    description: 'Find matching crypto tile pairs. Earn substantial multiplier bonuses for minimum steps and high speed.',
    activePlayers: 3120,
  },
  {
    id: 'coin_catcher',
    name: 'Coin Rush Runner',
    category: 'Action',
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    description: 'Catch falling golden tokens as they speed down the arena. Match the coin colors to earn score multipliers!',
    activePlayers: 5840,
  },
  {
    id: 'mines_sweeper',
    name: 'Block Mines',
    category: 'Casual',
    imageUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    description: 'Navigate through a grid and uncover safe tiles. Calculate multiplier safety or trigger explosive traps!',
    activePlayers: 2150,
  },
];

export const SURVEY_PROVIDERS: SurveyProvider[] = [
  {
    id: 'cpx_research',
    name: 'CPX Research',
    logoUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=120&auto=format&fit=crop&q=80',
    description: 'Premium surveys with global coverage. Pays out higher coins per minute of participation.',
    avgMinutes: 12,
    rewardCoins: 450,
  },
  {
    id: 'bitlabs',
    name: 'BitLabs',
    logoUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=120&auto=format&fit=crop&q=80',
    description: 'Interactive high-frequency surveys specifically matched to gamer profiles. Extremely low screening rate.',
    avgMinutes: 8,
    rewardCoins: 300,
  },
  {
    id: 'offertoro',
    name: 'OfferToro',
    logoUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=120&auto=format&fit=crop&q=80',
    description: 'Includes quick interactive surveys, multi-stage feedback panels, and rich digital product audits.',
    avgMinutes: 15,
    rewardCoins: 650,
  },
  {
    id: 'adgate_media',
    name: 'AdGate Media',
    logoUrl: 'https://images.unsplash.com/photo-1542744094-3a31f103e35f?w=120&auto=format&fit=crop&q=80',
    description: 'Watch video sequences or register for feedback trials to unlock secure immediate credits.',
    avgMinutes: 5,
    rewardCoins: 180,
  },
];

export const REWARD_ITEMS: RewardItem[] = [
  // Gift Cards
  {
    id: 'gift_card_amazon_50',
    category: 'Gift Cards',
    type: 'Gift Cards',
    brand: 'Amazon',
    title: 'Amazon Shopping Voucher - ₹50',
    description: 'Redeem an Indian Amazon Gift Card worth ₹50 instantly. Standard e-voucher rules apply.',
    imageUrl: 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?w=500&auto=format&fit=crop&q=80',
    coinCost: 5000,
    valueINR: 50,
    stock: 250,
  },
  {
    id: 'gift_card_amazon_100',
    category: 'Gift Cards',
    type: 'Gift Cards',
    brand: 'Amazon',
    title: 'Amazon Shopping Voucher - ₹100',
    description: 'Redeem an Indian Amazon Gift Card worth ₹100 instantly. Can be accumulated to pay for anything on Amazon Pay.',
    imageUrl: 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?w=500&auto=format&fit=crop&q=80',
    coinCost: 10000,
    valueINR: 100,
    stock: 120,
  },
  {
    id: 'gift_card_flipkart_100',
    category: 'Gift Cards',
    type: 'Gift Cards',
    brand: 'Flipkart',
    title: 'Flipkart E-Gift Voucher - ₹100',
    description: 'Get an instant ₹100 discount coupon for Flipkart. Valid across all lifestyle and digital shopping options.',
    imageUrl: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=500&auto=format&fit=crop&q=80',
    coinCost: 10000,
    valueINR: 100,
    stock: 180,
  },
  {
    id: 'gift_card_google_100',
    category: 'Gift Cards',
    type: 'Gift Cards',
    brand: 'Google Play',
    title: 'Google Play Gift Code - ₹100',
    description: 'Ready-to-use ₹100 Google Play standard recharge code. Buy games, movies, books, or in-app custom packages.',
    imageUrl: 'https://images.unsplash.com/photo-1614680376593-902f74fa0d41?w=500&auto=format&fit=crop&q=80',
    coinCost: 10000,
    valueINR: 100,
    stock: 95,
  },
  {
    id: 'gift_card_steam_250',
    category: 'Gift Cards',
    type: 'Gift Cards',
    brand: 'Steam',
    title: 'Steam Wallet Voucher - ₹250',
    description: 'Top up your Steam account with ₹250. Buy dynamic shooter, roleplay or retro desktop titles anywhere.',
    imageUrl: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=500&auto=format&fit=crop&q=80',
    coinCost: 25000,
    valueINR: 250,
    stock: 45,
  },
  {
    id: 'gift_card_amazon_500',
    category: 'Gift Cards',
    type: 'Gift Cards',
    brand: 'Amazon',
    title: 'Amazon Shopping Voucher - ₹500',
    description: 'Super ₹500 Amazon Gift Certificate. Valid for 1 full year from redemption. Instant code delivery.',
    imageUrl: 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?w=500&auto=format&fit=crop&q=80',
    coinCost: 50000,
    valueINR: 500,
    stock: 32,
  },

  // OTT, Shopping, Travel categories
  {
    id: 'ott_netflix_1',
    category: 'OTT',
    type: 'Coupons',
    brand: 'Netflix',
    title: 'Netflix Premium 1-Month Coupon',
    description: 'Apply at subscription checkout to stream unlimited UltraHD series, films, and originals.',
    imageUrl: 'https://images.unsplash.com/photo-1574375927938-d5a98e8edd86?w=500&auto=format&fit=crop&q=80',
    coinCost: 12000,
    valueINR: 199,
    stock: 50,
  },
  {
    id: 'ott_hotstar_3',
    category: 'OTT',
    type: 'Coupons',
    brand: 'Disney+ Hotstar',
    title: 'Hotstar Super 3-Months Premium',
    description: 'Get sports tournaments, international series, and blockbusters smoothly.',
    imageUrl: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=500&auto=format&fit=crop&q=80',
    coinCost: 18000,
    valueINR: 299,
    stock: 40,
  },
  {
    id: 'shopping_myntra_200',
    category: 'Shopping',
    type: 'Coupons',
    brand: 'Myntra',
    title: 'Myntra Flat ₹200 Promo Code',
    description: 'Applicable on fashion listings of ₹999 or more. Elevate your trend game without spending extra.',
    imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=500&auto=format&fit=crop&q=80',
    coinCost: 1000,
    valueINR: 200,
    stock: 1000,
  },
  {
    id: 'travel_ubereats_150',
    category: 'Travel',
    type: 'Digital Products',
    brand: 'Uber India',
    title: 'Uber Premier ₹150 Ride Voucher',
    description: 'Get Flat ₹150 off your comfortable city commute. Works instantly on Uber Premium or Auto.',
    imageUrl: 'https://images.unsplash.com/photo-1549576490-b0b4831ef60a?w=500&auto=format&fit=crop&q=80',
    coinCost: 13000,
    valueINR: 150,
    stock: 65,
  }
];

export const AFFILIATE_OFFERS: AffiliateOffer[] = [
  {
    id: 'aff_cuelinks_1',
    network: 'Cuelinks',
    brand: 'Ajio',
    title: 'Flat 12% Extra cashback on AJIO Trends',
    category: 'Fashion & Shopping',
    discountText: 'Use coupon AJIOSUPER on referral',
    directLink: 'https://ajio.com',
    earnCoins: 150,
    iconUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=80&auto=format&fit=crop&q=60',
    totalClicks: 1450,
  },
  {
    id: 'aff_earnkaro_2',
    network: 'EarnKaro',
    brand: 'Mamaearth',
    title: 'Flat ₹120 Cashback on baby care products',
    category: 'Cosmetics & Health',
    discountText: 'Earn guaranteed 150 coins after shipping',
    directLink: 'https://mamaearth.in',
    earnCoins: 250,
    iconUrl: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=80&auto=format&fit=crop&q=60',
    totalClicks: 840,
  },
  {
    id: 'aff_admitad_3',
    network: 'Admitad',
    brand: 'Hostinger India',
    title: 'Up to 30% discount + Premium Coin Bonus',
    category: 'Web Hosting & SaaS',
    discountText: 'Buy hosting using our direct link',
    directLink: 'https://hostinger.in',
    earnCoins: 800,
    iconUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=80&auto=format&fit=crop&q=60',
    totalClicks: 560,
  },
  {
    id: 'aff_vcommission_4',
    network: 'vCommission',
    brand: 'Domino\'s Pizza',
    title: 'Flat ₹50 Super discount + free delivery',
    category: 'Food & Dining',
    discountText: 'Valid on regular and premium crust pizzas',
    directLink: 'https://dominos.co.in',
    earnCoins: 120,
    iconUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=80&auto=format&fit=crop&q=60',
    totalClicks: 2190,
  }
];

export const ADVERTISER_CAMPAIGNS_SEED: AdvertiserCampaign[] = [
  {
    id: 'camp_yt_gaming',
    advertiserId: 'adv_royal_gamers',
    type: 'YouTube Promotion',
    title: 'Watch & Subscribe: Valorant Pro Arena Highlights',
    promotionUrl: 'https://youtube.com',
    promoBannerUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    targetClicks: 1000,
    currentClicks: 324,
    budgetINR: 500,
    isActive: true,
    createdAt: '2026-06-20T10:00:00.000Z',
  },
  {
    id: 'camp_web_earn',
    advertiserId: 'adv_fintech_labs',
    type: 'Website Promotion',
    title: 'Explore: Passive Income Secrets for Indian Students',
    promotionUrl: 'https://google.com',
    promoBannerUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop&q=80',
    targetClicks: 500,
    currentClicks: 412,
    budgetINR: 350,
    isActive: true,
    createdAt: '2026-06-21T12:30:00.000Z',
  },
  {
    id: 'camp_tele_trading',
    advertiserId: 'adv_crypto_alerts',
    type: 'Telegram Promotion',
    title: 'Join Telegram: Daily Free Signal alerts & Drops',
    promotionUrl: 'https://telegram.org',
    promoBannerUrl: 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?w=800&auto=format&fit=crop&q=80',
    targetClicks: 2000,
    currentClicks: 1109,
    budgetINR: 1000,
    isActive: true,
    createdAt: '2026-06-21T18:15:00.000Z',
  },
  {
    id: 'camp_app_arena',
    advertiserId: 'adv_indie_ventures',
    type: 'App Promotion',
    title: 'Download Game: Chess Battles Pro Android App',
    promotionUrl: 'https://play.google.com/store',
    promoBannerUrl: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&auto=format&fit=crop&q=80',
    targetClicks: 250,
    currentClicks: 148,
    budgetINR: 600,
    isActive: true,
    createdAt: '2026-06-22T02:00:00.000Z',
  }
];

export const TESTIMONIALS = [
  {
    id: 'test_1',
    name: 'Aravind Sharma',
    location: 'Mumbai',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    quote: 'Incredible platform! I played tap speed games in between classes and earned over 5000 coins in my first week. Cashed out a ₹50 Google Play voucher instantly.',
    rating: 5,
  },
  {
    id: 'test_2',
    name: 'Pooja Hegde',
    location: 'Bengaluru',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    quote: 'I purchased the Premium Weekly plan to unlock surveys. The CPX and BitLabs surveys are extremely fast. Already earned ₹100 inside 3 days. Highly recommended!',
    rating: 5,
  },
  {
    id: 'test_3',
    name: 'Tanmay Bhatt',
    location: 'Delhi',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    quote: 'Referral model is superb! Recommended 15 college friends. Earned immediate 100 coins peer conversion and upgraded to Monthly premium. Solid platform support.',
    rating: 5,
  }
];
